### ISSUE TITLE
EpisodePipeline not supported

### ISSUE THREAD

**Issue by ChangyaoTian** [CraftJarvis/MineStudio#2]
Hello, seems that `from minestudio.inference import EpisodePipeline` is currently unavailable, as the path of `minestudio/inference/pipeline` doesn't exist. Could you add the code for it? Thanks~

**Comment by muzhancun** [comment]
> Hello, seems that `from minestudio.inference import EpisodePipeline` is currently unavailable, as the path of `minestudio/inference/pipeline` doesn't exist. Could you add the code for it? Thanks~

Since EpisodePipeline is defined in minestudio.inference.__init__.py, it should be properly imported when you install minestudio via either pip install -e . or pip install minestudio. We would appreciate it if you could confirm this or share any additional information when using minestudio!
<img width="588" alt="image" src="https://github.com/user-attachments/assets/dcd121ff-23d4-42f0-b753-fcbdc45be7d3" />

**Comment by ChangyaoTian** [comment]
> Since EpisodePipeline is imported in minestudio.inference.__init__.py, ...
 
Yeah, but in `__init__.py`, it further imports the EpisodePipeline from `.pipeline`. But currently there is no file or folder named `pipeline` under this directory.

So I can get nothing but this error below if I run `from minestudio.inference import EpisodePipeline`:

`ModuleNotFoundError: No module named 'minestudio.inference.pipeline'`

**Comment by muzhancun** [comment]
> > Since EpisodePipeline is imported in minestudio.inference.**init**.py, ...
> 
> Yeah, but in `__init__.py`, it further imports the EpisodePipeline from `.pipeline`. But currently there is no file or folder named `pipeline` under this directory.
> 
> So I can get nothing but this error below if I run `from minestudio.inference import EpisodePipeline`:
> 
> `ModuleNotFoundError: No module named 'minestudio.inference.pipeline'`

Oh sorry, we have uploaded `minestudio.inference.pipeline.py`. Looking forward to more suggestions~
